sudo: required
services:
  - docker

before_install:
  - docker build -t atish9308/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true atish9308/client-test npm run test

after_success:
  - docker build -t atish9308/multi-client ./client
  - docker build -t atish9308/multi-nginx ./nginx
  - docker build -t atish9308/multi-server ./server
  - docker build -t atish9308/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub.
  - docker push atish9308/multi-client
  - docker push atish9308/multi-nginx
  - docker push atish9308/multi-server
  - docker push atish9308/multi-worker

